# Macros that can be included below; see yaml_includes.py.  Be careful in applying these:
# the include processor doesn't automatically flatten lists or anything like that.
includes:

    # ping is allowed from anywhere in just about every SG
    global-ping:
        proto: icmp
        ports: [-1]
        hosts:
          - 0.0.0.0/0

    # most outgoing flows are completely open
    global-any:
        proto: -1
        hosts:
          - 0.0.0.0/0

    jumphost-admin-access:
        proto: tcp
        ports: [22, 3389, 5900]
        hosts:
          - rejh1.srv.releng.mdc1.mozilla.com  # 10.49.48.100
          - rejh2.srv.releng.mdc1.mozilla.com  # 10.49.48.101
          - rejh1.srv.releng.mdc2.mozilla.com  # 10.51.48.100
          - rejh2.srv.releng.mdc2.mozilla.com  # 10.51.48.101

    nagios-nrpe:
        proto: tcp
        ports: [5666]
        hosts:
          - nagios1.private.releng.mdc1.mozilla.com
          - nagios1.private.releng.mdc2.mozilla.com

    outbound-http-https:
        proto: tcp
        ports: [80,443]
        hosts:
            - 0.0.0.0/0

    outbound-git:
        proto: tcp
        ports: [9418,22]  # N.B. allows SSH too
        hosts:
            - 192.30.252.0/22 # github (https://api.github.com/meta)
            - 198.145.11.235/32  # codeaurora

    outbound-amqp-amqps:
        proto: tcp
        ports: [5671, 5672]
        hosts:
            - orange-antelope.rmq.cloudamqp.com
            - orange-antelope-01.rmq.cloudamqp.com
            - orange-antelope-02.rmq.cloudamqp.com
            - orange-antelope-03.rmq.cloudamqp.com

    outbound-stun-tcp:
        proto: tcp
        ports: [42]
        hosts:
            - 23.21.150.121/32
            - expo.mit.edu
            - 216.93.246.14/32

    outbound-stun-udp:
        proto: udp
        ports: [42]
        hosts:
            - 23.21.150.121/32
            - expo.mit.edu
            - 216.93.246.14/32

    outbound-carbon:
        proto: tcp
        ports: [2003]
        hosts:
            - 0.0.0.0/0

    outbound-irc:
        proto: tcp
        ports: [6697]
        hosts:
            - 54.72.42.192/32
            - 54.219.165.167/32
            - 54.85.60.193/32
            - 63.245.216.214/32

    outbound-ntp:
        proto: udp
        ports: [123]
        hosts:
            - 0.0.0.0/0

    outbound-papertrail:
        proto: tcp
        ports: [45266]
        hosts:
            - 67.214.208.0/20
            - 173.247.96.0/19

    outbound-mozilla:
        # all outbound traffic to mozilla nets is filtered at the destination
        proto: -1
        hosts:
            # Private IP space
            - 10.0.0.0/8
            # Mozilla's public IP space
            - 63.245.208.0/20

    # network aliases:
    build-usw2: 10.132.52.0/22
    test-usw2: 10.132.56.0/22
    test2-usw2: 10.132.156.0/22
    test3-usw2: 10.132.40.0/21
    test4-usw2: 10.132.60.0/22
    try-usw2: 10.132.64.0/22
    build-use1: 10.134.52.0/22
    build2-use1: 10.134.164.0/24
    test-use1: 10.134.56.0/22
    test2-use1: 10.134.156.0/22
    test3-use1: 10.134.40.0/21
    test4-use1: 10.134.60.0/22
    test5-use1: 10.134.160.0/22
    try-use1: 10.134.64.0/22
    try2-use1: 10.134.165.0/24
    slave-vlans:
      - {include: build-usw2}
      - {include: test-usw2}
      - {include: test2-usw2}
      - {include: test3-usw2}
      - {include: test4-usw2}
      - {include: try-usw2}
      - {include: build-use1}
      - {include: build2-use1}
      - {include: test-use1}
      - {include: test2-use1}
      - {include: test3-use1}
      - {include: test4-use1}
      - {include: test5-use1}
      - {include: try-use1}
      - {include: try2-use1}

    # and port aliases
    buildbot-http-portrange: 8000-8999
    buildbot-rpc-portrange: 9000-9999

buildbot-master:
    description: security group for buildbot masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        # generic stuff
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

puppet-master:
    description: security group for puppet masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [443, 80, 8140]
          hosts:
            - 10.49.0.0/16
            - 10.51.0.0/16
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16
            - nagios1.private.releng.mdc1.mozilla.com
            - nagios1.private.releng.mdc2.mozilla.com

        # generic stuff
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

# proxxy is configured per-region; these two stanzas should be kept parallel
proxxy-vpc-use1:
    description: security group for proxxy servers in use1
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-use1}
            - {include: build2-use1}
            - {include: test-use1}
            - {include: test2-use1}
            - {include: test3-use1}
            - {include: test4-use1}
            - {include: test5-use1}
            - {include: try-use1}
            - {include: try2-use1}
            - nagios1.private.releng.mdc1.mozilla.com
            - nagios1.private.releng.mdc2.mozilla.com
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

proxxy-vpc-usw2:
    description: security group for proxxy servers in usw2
    regions:
        us-west-2: vpc-cd63f2a4
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-usw2}
            - {include: test-usw2}
            - {include: test2-usw2}
            - {include: test3-usw2}
            - {include: test4-usw2}
            - {include: try-usw2}
            - nagios1.private.releng.mdc1.mozilla.com
            - nagios1.private.releng.mdc2.mozilla.com
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

LogAggregators:
    description: Group for log aggregators and their load balancer
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [1514]
          hosts:            
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16
            - nagios1.private.releng.mdc1.mozilla.com
            - nagios1.private.releng.mdc2.mozilla.com
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

VCSSync:
    description: Group hg/git vcssync servers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

signing-worker:
    description: security group for signing workers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        # TODO: bug 1210137
        - include: global-any

addonworker:
    description: security group for addon_scriptworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

balrogworker:
    description: security group for balrogworkers
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

beetmoverworker:
    description: security group for beetmoverworkers
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

bouncerworker:
    description: security group for bouncer_scriptworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

pushapkworker:
    description: security group for pushapkworker
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

pushsnapworker:
    description: security group for pushsnap_scriptworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

shipitworker:
    description: security group for shipitworkers
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

binarytransparencyworker:
    description: security group for binary transparency worker
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any

treescriptworker:
    description: security group for treescriptworker
    regions:
        us-east-1: vpc-b42100df
        us-west-2: vpc-cd63f2a4
    inbound:
        - include: jumphost-admin-access
        - include: nagios-nrpe
        - include: global-ping
    outbound:
        - include: global-any
